[package]
name = "cargo-feature-test"
version = "0.1.0"
authors = ["Keunhong Lee <dlrmsghd@gmail.com>"]
edition = "2018"

[dependencies]
log = {version = "*"}
simple_logger = "*"

[features]
release_max_level_off = ["log/release_max_level_off"]